const Sequelize = require('sequelize')
const dbConfig = require('../config/database')

const Usuario = require('../models/Usuario')
const Tecnico = require('../models/Tecnico')
const Proprietario = require('../models/Proprietario')
const Propriedade = require('../models/Propriedade')
const PropriedadeTecnico = require('../models/PropriedadeTecnico')
const InfoPropriedade = require('../models/InfoPropriedade')
const Folhagem = require('../models/Forragem')
const TerraForragem = require('../models/TerraForragem')

const Animal = require('../models/Animal')
const Parto = require('../models/Parto')
const Inseminacao = require('../models/Inseminacao')
const Prenhez = require('../models/Prenhez')
const Mastite = require('../models/Mastite')
const Tratamento = require('../models/Tratamento')
const Medicamento = require('../models/Medicamento')
const Doenca = require('../models/Doenca')
const VendaAnimal = require('../models/VendaAnimal')
const CompraAnimal = require('../models/CompraAnimal')
const Morte = require('../models/Morte')

const connection = new Sequelize(dbConfig)

Usuario.init(connection)
Tecnico.init(connection)
Proprietario.init(connection)
Propriedade.init(connection)
PropriedadeTecnico.init(connection)
InfoPropriedade.init(connection)
Folhagem.init(connection)
TerraForragem.init(connection)

Animal.init(connection)
Parto.init(connection)
Inseminacao.init(connection)
Prenhez.init(connection)
Mastite.init(connection)
Medicamento.init(connection)
Tratamento.init(connection)
Doenca.init(connection)
VendaAnimal.init(connection)
CompraAnimal.init(connection)
Morte.init(connection)

Usuario.associate(connection.models)
Tecnico.associate(connection.models)
Proprietario.associate(connection.models)
Propriedade.associate(connection.models)
PropriedadeTecnico.associate(connection.models)
InfoPropriedade.associate(connection.models)
TerraForragem.associate(connection.models)

Animal.associate(connection.models)
Parto.associate(connection.models)
Inseminacao.associate(connection.models)
Prenhez.associate(connection.models)
Mastite.associate(connection.models)
Tratamento.associate(connection.models)
Doenca.associate(connection.models)
VendaAnimal.associate(connection.models)
CompraAnimal.associate(connection.models)
Morte.associate(connection.models)

module.exports = connection
